In [165]:
from sklearn.preprocessing import LabelEncoder
result = pd.DataFrame({
            "X": ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm'],
            "Y": ['what', 'this', 'is', 'what', 'is', 'what', 'this', ]})
lle = LabelEncoder()
result['Z'] = lle.fit_transform(result['X'])
result

      X     Y  Z
0  cold  what  0
1  cold  this  0
2  warm    is  2
3  cold  what  0
4   hot    is  1
5   hot  what  1
6  warm  this  2

In [166]:
import pandas as pd

result = pd.DataFrame({
            "X": ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm'],
            "Y": ['what', 'this', 'is', 'what', 'is', 'what', 'this', ]})
result = pd.get_dummies(result)
result

   X_cold  X_hot  X_warm  Y_is  Y_this  Y_what
0       1      0       0     0       0       1
1       1      0       0     0       1       0
2       0      0       1     1       0       0
3       1      0       0     0       0       1
4       0      1       0     1       0       0
5       0      1       0     0       0       1
6       0      0       1     0       1       0

In [167]:
#If you read the docs for OneHotEncoder you'll see the input for fit is "Input array of type int". 
#So you need to do two steps for your one hot encoded data
import pandas as pd
from collections import defaultdict
from sklearn.preprocessing import OneHotEncoder
result = pd.DataFrame({
            "X": ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm'],
            "Y": ['what', 'this', 'is', 'what', 'is', 'what', 'this', ]})


d = defaultdict(LabelEncoder)
result = result.apply(lambda x: d[x.name].fit_transform(x))
result

   X  Y
0  0  2
1  0  1
2  2  0
3  0  2
4  1  0
5  1  2
6  2  1

In [168]:
OHE = OneHotEncoder(handle_unknown='ignore')
result = OHE.fit_transform(result).toarray()
result

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0.]])